Traceback (most recent call last):
  File "/Users/derekli/Documents/2048/main/test/random_ai_test.py", line 4, in <module>
    from random_ai import Random_AI
  File "../random_ai.py", line 1, in <module>
    from ai import AI
  File "../ai.py", line 15
    
    ^
SyntaxError: unexpected EOF while parsing
>>> 